import { theme } from "@/styles/theme";
import { CssBaseline, Box, ThemeProvider } from "@mui/material";
import type { Metadata } from "next";
import { NavBar } from "@/components/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Box sx={{ p: 0, m: 0 }}>
            <NavBar />
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
